//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSService.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IWCFService")]
    public interface IWCFService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetNumberOfCars", ReplyAction="http://tempuri.org/IWCFService/GetNumberOfCarsResponse")]
        int GetNumberOfCars();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetNumberOfCars", ReplyAction="http://tempuri.org/IWCFService/GetNumberOfCarsResponse")]
        System.Threading.Tasks.Task<int> GetNumberOfCarsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/ShowMessageOnServerSide", ReplyAction="http://tempuri.org/IWCFService/ShowMessageOnServerSideResponse")]
        void ShowMessageOnServerSide(string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/ShowMessageOnServerSide", ReplyAction="http://tempuri.org/IWCFService/ShowMessageOnServerSideResponse")]
        System.Threading.Tasks.Task ShowMessageOnServerSideAsync(string msg);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFServiceChannel : CMSService.ServiceReference.IWCFService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFServiceClient : System.ServiceModel.ClientBase<CMSService.ServiceReference.IWCFService>, CMSService.ServiceReference.IWCFService {
        
        public WCFServiceClient() {
        }
        
        public WCFServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetNumberOfCars() {
            return base.Channel.GetNumberOfCars();
        }
        
        public System.Threading.Tasks.Task<int> GetNumberOfCarsAsync() {
            return base.Channel.GetNumberOfCarsAsync();
        }
        
        public void ShowMessageOnServerSide(string msg) {
            base.Channel.ShowMessageOnServerSide(msg);
        }
        
        public System.Threading.Tasks.Task ShowMessageOnServerSideAsync(string msg) {
            return base.Channel.ShowMessageOnServerSideAsync(msg);
        }
    }
}
